sonar.projectKey=Avance_proyecto_software
sonar.organization=SUMTOPROVE
sonar.projectName=Avance_proyecto_software
sonar.sources=server
sonar.tests=server/tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
